//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information Management.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to search project.
        /// </summary>
        public static string BackToSearchProject {
            get {
                return ResourceManager.GetString("BackToSearchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the project(s) with number:.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete project(s).
        /// </summary>
        public static string ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("ConfirmDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to leave this page, the process will not be saved?.
        /// </summary>
        public static string ConfirmGoHome {
            get {
                return ResourceManager.GetString("ConfirmGoHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to homepage.
        /// </summary>
        public static string ConfirmGoHomeTitle {
            get {
                return ResourceManager.GetString("ConfirmGoHomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact your administrator.
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to when you try to create a new project with project number:.
        /// </summary>
        public static string CreateANewProject {
            get {
                return ResourceManager.GetString("CreateANewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string CreateProject {
            get {
                return ResourceManager.GetString("CreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer field is not longer than 50 characters.
        /// </summary>
        public static string CustomerTooLongError {
            get {
                return ResourceManager.GetString("CustomerTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer is required.
        /// </summary>
        public static string CutomerRequireError {
            get {
                return ResourceManager.GetString("CutomerRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date only.
        /// </summary>
        public static string DateOnlyError {
            get {
                return ResourceManager.GetString("DateOnlyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete the project(s) which have the following project number.
        /// </summary>
        public static string DeleteProjectsByProjectNumber {
            get {
                return ResourceManager.GetString("DeleteProjectsByProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete selected item(s).
        /// </summary>
        public static string DeleteSelectedItems {
            get {
                return ResourceManager.GetString("DeleteSelectedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string EditProject {
            get {
                return ResourceManager.GetString("EditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project Information.
        /// </summary>
        public static string EditProjectInfor {
            get {
                return ResourceManager.GetString("EditProjectInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date must be later than start date.
        /// </summary>
        public static string EndDateEalierThanStartDateError {
            get {
                return ResourceManager.GetString("EndDateEalierThanStartDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all the mandatory fields (*)..
        /// </summary>
        public static string ErrorMandatoryField {
            get {
                return ResourceManager.GetString("ErrorMandatoryField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occur at data access layer when you try to .
        /// </summary>
        public static string ErrorOccurAtDataAccess {
            get {
                return ResourceManager.GetString("ErrorOccurAtDataAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find all employees.
        /// </summary>
        public static string FindAllEmployees {
            get {
                return ResourceManager.GetString("FindAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find all groups.
        /// </summary>
        public static string FindAllGroups {
            get {
                return ResourceManager.GetString("FindAllGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find all projects.
        /// </summary>
        public static string FindAllProjects {
            get {
                return ResourceManager.GetString("FindAllProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find employees by the following visas.
        /// </summary>
        public static string FindEmployeesByVisas {
            get {
                return ResourceManager.GetString("FindEmployeesByVisas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find the group which has name.
        /// </summary>
        public static string FindGroupByGroupName {
            get {
                return ResourceManager.GetString("FindGroupByGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to find project by project number.
        /// </summary>
        public static string FindProjectByProjectNumber {
            get {
                return ResourceManager.GetString("FindProjectByProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following project number already exists.
        /// </summary>
        public static string FollowingProjectNumberAlreadyExist {
            get {
                return ResourceManager.GetString("FollowingProjectNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group is required.
        /// </summary>
        public static string GroupRequireError {
            get {
                return ResourceManager.GetString("GroupRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group name does not exist.
        /// </summary>
        public static string InvalidGroupNameError {
            get {
                return ResourceManager.GetString("InvalidGroupNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The followiing visas do not exist.
        /// </summary>
        public static string InvalidVisasError {
            get {
                return ResourceManager.GetString("InvalidVisasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item(s) selected.
        /// </summary>
        public static string ItemsSelected {
            get {
                return ResourceManager.GetString("ItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project name is not longer than 50 characters.
        /// </summary>
        public static string NameTooLongError {
            get {
                return ResourceManager.GetString("NameTooLongError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string NewProject {
            get {
                return ResourceManager.GetString("NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or.
        /// </summary>
        public static string or {
            get {
                return ResourceManager.GetString("or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        public static string ProjectList {
            get {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name is required.
        /// </summary>
        public static string ProjectNameRequireError {
            get {
                return ResourceManager.GetString("ProjectNameRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number.
        /// </summary>
        public static string ProjectNumber {
            get {
                return ResourceManager.GetString("ProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project number already exist. Please select a different number..
        /// </summary>
        public static string ProjectNumberAlreadyExist {
            get {
                return ResourceManager.GetString("ProjectNumberAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project number must have value from 1000 to 9999.
        /// </summary>
        public static string ProjectNumberRangeError {
            get {
                return ResourceManager.GetString("ProjectNumberRangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number is required.
        /// </summary>
        public static string ProjectNumberRequireError {
            get {
                return ResourceManager.GetString("ProjectNumberRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Search.
        /// </summary>
        public static string ResetSearch {
            get {
                return ResourceManager.GetString("ResetSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, name, customer.
        /// </summary>
        public static string SearchCriteria {
            get {
                return ResourceManager.GetString("SearchCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Project.
        /// </summary>
        public static string SearchProject {
            get {
                return ResourceManager.GetString("SearchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project with the following project number has been updated since the last time you load it: .
        /// </summary>
        public static string StaleProjectError {
            get {
                return ResourceManager.GetString("StaleProjectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date is required.
        /// </summary>
        public static string StartDateRequireError {
            get {
                return ResourceManager.GetString("StartDateRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string StatusFIN {
            get {
                return ResourceManager.GetString("StatusFIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string StatusINP {
            get {
                return ResourceManager.GetString("StatusINP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string StatusNEW {
            get {
                return ResourceManager.GetString("StatusNEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string StatusPLA {
            get {
                return ResourceManager.GetString("StatusPLA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status is required.
        /// </summary>
        public static string StatusRequireError {
            get {
                return ResourceManager.GetString("StatusRequireError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Project.
        /// </summary>
        public static string TitleCreateProject {
            get {
                return ResourceManager.GetString("TitleCreateProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string TitleEditProject {
            get {
                return ResourceManager.GetString("TitleEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Project.
        /// </summary>
        public static string TitleListProject {
            get {
                return ResourceManager.GetString("TitleListProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error Occurred.
        /// </summary>
        public static string UnexpectedErrorOccurred {
            get {
                return ResourceManager.GetString("UnexpectedErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update project by project number.
        /// </summary>
        public static string UpdateProjectByProjectNumber {
            get {
                return ResourceManager.GetString("UpdateProjectByProjectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
